version: '3'

services:
  db:
    privileged: true
    image: mysql:8.0.30
    container_name: antenna-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Antenna@58.com
      MYSQL_DATABASE: antenna
    networks:
      - antenna
    restart: always


  antenna:
    build: ./
    image: antenna:latest
    depends_on:
      - db
    container_name: antenna
    volumes:
      - ./:/antenna
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./conf/antenna.ini
        target: /etc/supervisor.d/antenna.ini
    ports:
      - "21:21"
      - "80:80"
      - "2345:2345"
      - "53:53/udp"
      - "443:443"
    environment:
      # 平台数据库配置，与上mysql配置保持一致
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Antenna@58.com
      # 平台配置
      PLATFORM_DOMAIN: test.com
      PLATFORM_ENVIROMENT: docker
      #登陆页面路径，如设置成abc 则登陆页面地址为http://platform.com/abc
      LOGIN_PATH: ''
      PLATFORM_ROOT_USER: antenna@58.com
      PLATFORM_ROOT_PWD: antenna@58.com
      # DNS配置
      DNS_DOMAIN: test.cn
      NS1_DOMAIN: ns1.test.cn
      NS2_DOMAIN: ns2.test.cn
      SERVER_IP: 127.0.0.1

    networks:
      - antenna
    restart: always

networks:
  antenna:
    driver: bridge
